#pragma once

#include <uORB/Subscription.hpp>
#include <uORB/Publication.hpp>
#include <uORB/topics/latency_ping.h>
#include <uORB/topics/latency_pong.h>

class SyncTimers
{
public:
	int run();

private:
	void pingPongLoop();

	// listens for ping from Jetson. Sub reads raw bytes, no msg type declaration needed. Topic is 'latency_ping'
	uORB::Subscription _ping_sub{ORB_ID(latency_ping)};
	// sends pong back to Jetson. Declare msg type as 'latency_pong_s'. Topic is 'latency_pong'
	// latency_pong_s (struct) is automatically generated by uORB from latency_pong.msg
	uORB::Publication<latency_pong_s> _pong_pub{ORB_ID(latency_pong)};
};
